name: CI Workflow

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: info
        run: echo "Hello from test3 ${{ github.Workflow }} triggered by the ${{ github.event_name }} done by ${{ github.actor }}"

      - name: lint
        run: make lint

      - name: test
        run: make test

      - name: build
        run: make build

      - name: check app
        run: make check_app
